### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRQ0lrZkJUZFJXazhoNEhIMFFNZU1nZzhUNTV1aTVkSlZxcFgwK29OVkNJPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjUwNzgyMDI0LCJleHAiOjE2NTA4Njg0MjR9.g60EUFj8sTg_Sr6m8VYwedgUzSXiF7vqrjY6l7PNtSA

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스"
}
### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRQ0lrZkJUZFJXazhoNEhIMFFNZU1nZzhUNTV1aTVkSlZxcFgwK29OVkNJPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjUwNzgyMDI0LCJleHAiOjE2NTA4Njg0MjR9.g60EUFj8sTg_Sr6m8VYwedgUzSXiF7vqrjY6l7PNtSA

{
      "productId": 1,
      "count": 1,
      "name": "280",
      "price": 100000
}

### 이메일 인증 ( 고객 )
GET http://localhost:8081/signup/customer/verify?email=ewb.doohyun@gmail.com&code=c8oNfeln0A
